# Generated by Django 6.0.1 on 2026-02-02 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('founded', models.IntegerField(blank=True, null=True)),
                ('stadium', models.CharField(blank=True, max_length=100, null=True)),
                ('short_name', models.CharField(blank=True, max_length=20, null=True)),
                ('seed_rank', models.PositiveIntegerField(blank=True, help_text='Lower = stronger seed (1 is top seed). Leave blank for unseeded.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='KnockoutRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_type', models.CharField(choices=[('R16', 'Round of 16'), ('QF', 'Quarterfinals'), ('SF', 'Semifinals'), ('F', 'Final'), ('3P', 'Third Place Match')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=20)),
                ('preferred_club', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(choices=[('ST', 'ST'), ('LW', 'LW / LM'), ('RW', 'RW / RM'), ('CM', 'CM'), ('CDM', 'CDM'), ('CAM', 'CAM'), ('LB', 'LB'), ('CB', 'CB'), ('RB', 'RB'), ('GK', 'GK'), ('ANY', 'ANY')], max_length=10)),
                ('region', models.CharField(blank=True, choices=[('PK', 'Pakistan'), ('ME', 'Middle East'), ('EU', 'Europe'), ('OT', 'Other')], max_length=10, null=True)),
                ('platform', models.CharField(blank=True, choices=[('PS5', 'PlayStation 5'), ('PC', 'PC'), ('XBOX', 'Xbox')], max_length=10, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TeamRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('founded', models.CharField(blank=True, max_length=50, null=True)),
                ('stadium', models.CharField(blank=True, max_length=100, null=True)),
                ('platform', models.CharField(blank=True, choices=[('PS5', 'PlayStation 5'), ('PC', 'PC'), ('XBOX', 'Xbox')], max_length=10, null=True)),
                ('region', models.CharField(blank=True, choices=[('PK', 'Pakistan'), ('ME', 'Middle East'), ('EU', 'Europe'), ('OT', 'Other')], max_length=10, null=True)),
                ('captain_name', models.CharField(max_length=100)),
                ('captain_whatsapp', models.CharField(max_length=20)),
                ('captain_position', models.CharField(choices=[('ST', 'ST'), ('LW', 'LW / LM'), ('RW', 'RW / RM'), ('CM', 'CM'), ('CDM', 'CDM'), ('CAM', 'CAM'), ('LB', 'LB'), ('CB', 'CB'), ('RB', 'RB'), ('GK', 'GK'), ('ANY', 'ANY')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('week_number', models.IntegerField(blank=True, null=True)),
                ('away_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_fixtures', to='league.club')),
                ('home_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_fixtures', to='league.club')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='league.group')),
            ],
        ),
        migrations.CreateModel(
            name='KnockoutMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_placeholder', models.CharField(blank=True, max_length=10, null=True)),
                ('away_placeholder', models.CharField(blank=True, max_length=10, null=True)),
                ('home_goals', models.IntegerField(default=0)),
                ('away_goals', models.IntegerField(default=0)),
                ('is_played', models.BooleanField(default=False)),
                ('away_club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knockout_away', to='league.club')),
                ('home_club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knockout_home', to='league.club')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='league.knockoutround')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamertag', models.CharField(max_length=100, verbose_name='Name/Gamertag')),
                ('platform', models.CharField(choices=[('PS5', 'PlayStation 5'), ('XBOX', 'Xbox'), ('PC', 'PC')], max_length=10)),
                ('position', models.CharField(max_length=50)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='league.club')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_goals', models.IntegerField(default=0)),
                ('away_goals', models.IntegerField(default=0)),
                ('is_played', models.BooleanField(default=False)),
                ('fixture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group_match', to='league.fixture')),
                ('away_players', models.ManyToManyField(blank=True, related_name='away_group_matches', to='league.player')),
                ('home_players', models.ManyToManyField(blank=True, related_name='home_group_matches', to='league.player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerMatchStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('minutes_played', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('group_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='league.groupmatch')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_stats', to='league.player')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('clubs', models.ManyToManyField(blank=True, related_name='seasons', to='league.club')),
            ],
        ),
        migrations.AddField(
            model_name='knockoutround',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knockout_rounds', to='league.season'),
        ),
        migrations.AddField(
            model_name='group',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='league.season'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixtures', to='league.season'),
        ),
        migrations.CreateModel(
            name='SeasonAwards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_defender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defender_awards', to='league.player')),
                ('best_midfielder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='midfielder_awards', to='league.player')),
                ('mvp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mvp_awards', to='league.player')),
                ('season', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='league.season')),
                ('top_assister', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playmaker_awards', to='league.player')),
                ('top_scorer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='golden_boot_awards', to='league.player')),
            ],
        ),
        migrations.CreateModel(
            name='TeamRegistrationPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('ST', 'ST'), ('LW', 'LW / LM'), ('RW', 'RW / RM'), ('CM', 'CM'), ('CDM', 'CDM'), ('CAM', 'CAM'), ('LB', 'LB'), ('CB', 'CB'), ('RB', 'RB'), ('GK', 'GK'), ('ANY', 'ANY')], max_length=10)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='league.teamregistration')),
            ],
        ),
        migrations.CreateModel(
            name='TeamSeasonStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('goals_for', models.IntegerField(default=0)),
                ('goals_against', models.IntegerField(default=0)),
                ('goal_difference', models.IntegerField(default=0)),
                ('clean_sheets', models.IntegerField(default=0)),
                ('finish_position', models.CharField(blank=True, choices=[('champion', 'Champion'), ('runner_up', 'Runner Up'), ('third', 'Third Place'), ('semis', 'Semi Finalist'), ('groups', 'Group Stage')], max_length=20, null=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.club')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_entries', to='league.club')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='league.group')),
            ],
            options={
                'unique_together': {('group', 'club')},
            },
        ),
        migrations.CreateModel(
            name='PlayerSeasonStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('clean_sheets', models.IntegerField(default=0)),
                ('appearances', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('manual', models.BooleanField(default=False)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_season_stats', to='league.club')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_stats', to='league.player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='league.season')),
            ],
            options={
                'unique_together': {('player', 'season')},
            },
        ),
    ]
