# Generated by Django 6.0.1 on 2026-01-29 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamseasonstats',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='teamseasonstats',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='teamseasonstats',
            name='finish_position',
            field=models.CharField(blank=True, choices=[('champion', 'Champion'), ('runner_up', 'Runner Up'), ('third', 'Third Place'), ('semis', 'Semi Finalist'), ('groups', 'Group Stage')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teamseasonstats',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.season'),
        ),
        migrations.AlterField(
            model_name='teamseasonstats',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.club'),
        ),
        migrations.RemoveField(
            model_name='teamseasonstats',
            name='goals_against',
        ),
        migrations.RemoveField(
            model_name='teamseasonstats',
            name='goals_for',
        ),
    ]
