# Generated by Django 6.0.1 on 2026-02-03 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermatchstats',
            name='fixture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='league.fixture'),
        ),
        migrations.AddField(
            model_name='playermatchstats',
            name='knockout_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='league.knockoutmatch'),
        ),
    ]
