# Generated by Django 6.0.1 on 2026-02-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_playermatchstats_fixture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knockoutmatch',
            name='away_players',
            field=models.ManyToManyField(blank=True, related_name='away_knockout_matches', to='league.player'),
        ),
        migrations.AddField(
            model_name='knockoutmatch',
            name='home_players',
            field=models.ManyToManyField(blank=True, related_name='home_knockout_matches', to='league.player'),
        ),
    ]
