# Generated by Django 6.0.1 on 2026-01-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_alter_teamseasonstats_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamseasonstats',
            name='clean_sheets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamseasonstats',
            name='goal_difference',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamseasonstats',
            name='goals_against',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamseasonstats',
            name='goals_for',
            field=models.IntegerField(default=0),
        ),
    ]
