# Generated by Django 6.0.1 on 2026-02-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_knockoutmatch_away_players_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='league/pplLogos/'),
        ),
    ]
