# Generated by Django 6.0.1 on 2026-01-30 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_teamseasonstats_clean_sheets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_players',
            field=models.ManyToManyField(blank=True, related_name='away_matches', to='league.player'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_players',
            field=models.ManyToManyField(blank=True, related_name='home_matches', to='league.player'),
        ),
        migrations.AlterField(
            model_name='playerseasonstats',
            name='manual',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='league.season')),
            ],
        ),
        migrations.AddField(
            model_name='fixture',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='league.group'),
        ),
        migrations.CreateModel(
            name='KnockoutRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_type', models.CharField(choices=[('R16', 'Round of 16'), ('QF', 'Quarterfinals'), ('SF', 'Semifinals'), ('F', 'Final'), ('3P', 'Third Place Match')], max_length=3)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knockout_rounds', to='league.season')),
            ],
        ),
        migrations.CreateModel(
            name='KnockoutMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_goals', models.IntegerField(default=0)),
                ('away_goals', models.IntegerField(default=0)),
                ('is_played', models.BooleanField(default=False)),
                ('away_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knockout_away', to='league.club')),
                ('home_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knockout_home', to='league.club')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='league.knockoutround')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_entries', to='league.club')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='league.group')),
            ],
            options={
                'unique_together': {('group', 'club')},
            },
        ),
    ]
