# Generated by Django 6.0.1 on 2026-02-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_club_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
