# Generated by Django 6.0.1 on 2026-01-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_match_away_players_match_home_players_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='seed_rank',
            field=models.PositiveIntegerField(blank=True, help_text='Lower = stronger seed (1 is top seed). Leave blank for unseeded.', null=True),
        ),
    ]
