# Generated by Django 6.0.1 on 2026-01-30 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_club_seed_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=20)),
                ('preferred_club', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(choices=[('ST', 'ST'), ('LW', 'LW / LM'), ('RW', 'RW / RM'), ('CM', 'CM'), ('CDM', 'CDM'), ('CAM', 'CAM'), ('LB', 'LB'), ('CB', 'CB'), ('RB', 'RB'), ('GK', 'GK'), ('ANY', 'ANY')], max_length=10)),
                ('region', models.CharField(blank=True, choices=[('PK', 'Pakistan'), ('ME', 'Middle East'), ('EU', 'Europe'), ('OT', 'Other')], max_length=10, null=True)),
                ('platform', models.CharField(blank=True, choices=[('PS5', 'PlayStation 5'), ('PC', 'PC'), ('XBOX', 'Xbox')], max_length=10, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TeamRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('founded', models.CharField(blank=True, max_length=50, null=True)),
                ('stadium', models.CharField(blank=True, max_length=100, null=True)),
                ('platform', models.CharField(blank=True, choices=[('PS5', 'PlayStation 5'), ('PC', 'PC'), ('XBOX', 'Xbox')], max_length=10, null=True)),
                ('region', models.CharField(blank=True, choices=[('PK', 'Pakistan'), ('ME', 'Middle East'), ('EU', 'Europe'), ('OT', 'Other')], max_length=10, null=True)),
                ('captain_name', models.CharField(max_length=100)),
                ('captain_whatsapp', models.CharField(max_length=20)),
                ('captain_position', models.CharField(choices=[('ST', 'ST'), ('LW', 'LW / LM'), ('RW', 'RW / RM'), ('CM', 'CM'), ('CDM', 'CDM'), ('CAM', 'CAM'), ('LB', 'LB'), ('CB', 'CB'), ('RB', 'RB'), ('GK', 'GK'), ('ANY', 'ANY')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TeamRegistrationPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('ST', 'ST'), ('LW', 'LW / LM'), ('RW', 'RW / RM'), ('CM', 'CM'), ('CDM', 'CDM'), ('CAM', 'CAM'), ('LB', 'LB'), ('CB', 'CB'), ('RB', 'RB'), ('GK', 'GK'), ('ANY', 'ANY')], max_length=10)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='league.teamregistration')),
            ],
        ),
    ]
