# Generated by Django 6.0.1 on 2026-02-20 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_alter_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermatchstats',
            name='man_of_the_match',
            field=models.BooleanField(default=False),
        ),
    ]
