# Generated by Django 6.0.1 on 2026-01-30 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0006_playerregistration_teamregistration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='clubs',
            field=models.ManyToManyField(blank=True, related_name='seasons', to='league.club'),
        ),
        migrations.AlterField(
            model_name='season',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='season',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
