# Generated by Django 6.0.1 on 2026-02-24 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0006_playermatchstats_man_of_the_match'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fixture',
            index=models.Index(fields=['season', 'date'], name='league_fixt_season__3326e1_idx'),
        ),
        migrations.AddIndex(
            model_name='fixture',
            index=models.Index(fields=['season', 'week_number'], name='league_fixt_season__12a787_idx'),
        ),
        migrations.AddIndex(
            model_name='fixture',
            index=models.Index(fields=['season', 'group'], name='league_fixt_season__16397f_idx'),
        ),
        migrations.AddIndex(
            model_name='playermatchstats',
            index=models.Index(fields=['player', 'group_match'], name='league_play_player__025566_idx'),
        ),
        migrations.AddIndex(
            model_name='playermatchstats',
            index=models.Index(fields=['player', 'knockout_match'], name='league_play_player__c2756b_idx'),
        ),
        migrations.AddIndex(
            model_name='playermatchstats',
            index=models.Index(fields=['group_match', 'rating'], name='league_play_group_m_158c47_idx'),
        ),
        migrations.AddIndex(
            model_name='playermatchstats',
            index=models.Index(fields=['man_of_the_match'], name='league_play_man_of__990463_idx'),
        ),
        migrations.AddIndex(
            model_name='playerseasonstats',
            index=models.Index(fields=['season', 'player'], name='league_play_season__49f2b1_idx'),
        ),
        migrations.AddIndex(
            model_name='playerseasonstats',
            index=models.Index(fields=['season', '-rating', '-goals', '-assists'], name='league_play_season__3b26b5_idx'),
        ),
        migrations.AddIndex(
            model_name='playerseasonstats',
            index=models.Index(fields=['season', '-goals', '-assists'], name='league_play_season__e736b2_idx'),
        ),
        migrations.AddIndex(
            model_name='playerseasonstats',
            index=models.Index(fields=['season', 'appearances'], name='league_play_season__02a96a_idx'),
        ),
        migrations.AddIndex(
            model_name='teamseasonstats',
            index=models.Index(fields=['season', 'team'], name='league_team_season__64375a_idx'),
        ),
        migrations.AddIndex(
            model_name='teamseasonstats',
            index=models.Index(fields=['season', '-points', '-goal_difference', '-goals_for'], name='league_team_season__c28b74_idx'),
        ),
    ]
