# Generated by Django 6.0.1 on 2026-02-24 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0007_fixture_league_fixt_season__3326e1_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamOfTheWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField(help_text='Week number (1, 2, 3, etc.)')),
                ('week_type', models.CharField(choices=[('GW', 'Gameweek'), ('KO', 'Knockout Stage'), ('TOTS', 'Team of the Season')], default='GW', max_length=4)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False, help_text='Make this TOTW visible on the website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-season__year', 'week_type', 'week_number'],
            },
        ),
        migrations.CreateModel(
            name='TeamOfTheWeekSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('ATT', 'Attacker'), ('MID', 'Midfielder'), ('DEF', 'Defender'), ('GK', 'Goalkeeper')], help_text='Position for this TOTW selection', max_length=3)),
                ('games_played', models.IntegerField(default=0)),
                ('goals', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('clean_sheets', models.IntegerField(default=0)),
                ('avg_rating', models.FloatField(default=0)),
                ('lineup_position', models.IntegerField(default=0, help_text='Position in lineup for display (1-11)')),
            ],
            options={
                'ordering': ['lineup_position'],
            },
        ),
        migrations.AddField(
            model_name='playermatchstats',
            name='position_played',
            field=models.CharField(blank=True, choices=[('ATT', 'Attacker'), ('MID', 'Midfielder'), ('DEF', 'Defender'), ('GK', 'Goalkeeper')], help_text='Position played in this match (for TOTW selection)', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='playerseasonstats',
            name='skill_rating',
            field=models.FloatField(default=0, help_text='Weighted average rating accounting for games played'),
        ),
        migrations.AlterField(
            model_name='playerregistration',
            name='position',
            field=models.CharField(choices=[('ST', 'Striker'), ('LW', 'Left Wing'), ('RW', 'Right Wing'), ('CM', 'Central Midfielder'), ('CDM', 'Defensive Midfielder'), ('CAM', 'Attacking Midfielder'), ('LB', 'Left Back'), ('CB', 'Centre Back'), ('RB', 'Right Back'), ('GK', 'Goalkeeper'), ('ANY', 'Any Position')], max_length=10),
        ),
        migrations.AlterField(
            model_name='teamregistration',
            name='captain_position',
            field=models.CharField(choices=[('ST', 'Striker'), ('LW', 'Left Wing'), ('RW', 'Right Wing'), ('CM', 'Central Midfielder'), ('CDM', 'Defensive Midfielder'), ('CAM', 'Attacking Midfielder'), ('LB', 'Left Back'), ('CB', 'Centre Back'), ('RB', 'Right Back'), ('GK', 'Goalkeeper'), ('ANY', 'Any Position')], max_length=10),
        ),
        migrations.AlterField(
            model_name='teamregistrationplayer',
            name='position',
            field=models.CharField(choices=[('ST', 'Striker'), ('LW', 'Left Wing'), ('RW', 'Right Wing'), ('CM', 'Central Midfielder'), ('CDM', 'Defensive Midfielder'), ('CAM', 'Attacking Midfielder'), ('LB', 'Left Back'), ('CB', 'Centre Back'), ('RB', 'Right Back'), ('GK', 'Goalkeeper'), ('ANY', 'Any Position')], max_length=10),
        ),
        migrations.AddIndex(
            model_name='playermatchstats',
            index=models.Index(fields=['position_played', '-rating'], name='league_play_positio_f20f4a_idx'),
        ),
        migrations.AddIndex(
            model_name='playerseasonstats',
            index=models.Index(fields=['season', '-skill_rating'], name='league_play_season__a6065e_idx'),
        ),
        migrations.AddField(
            model_name='teamoftheweek',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_of_weeks', to='league.season'),
        ),
        migrations.AddField(
            model_name='teamoftheweekselection',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='totw_selections', to='league.player'),
        ),
        migrations.AddField(
            model_name='teamoftheweekselection',
            name='totw',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='league.teamoftheweek'),
        ),
        migrations.AddIndex(
            model_name='teamoftheweek',
            index=models.Index(fields=['season', 'week_type', 'week_number'], name='league_team_season__c10fcc_idx'),
        ),
        migrations.AddIndex(
            model_name='teamoftheweek',
            index=models.Index(fields=['is_published', '-created_at'], name='league_team_is_publ_2acfd1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teamoftheweek',
            unique_together={('season', 'week_number', 'week_type')},
        ),
        migrations.AddIndex(
            model_name='teamoftheweekselection',
            index=models.Index(fields=['totw', 'position'], name='league_team_totw_id_f2470c_idx'),
        ),
        migrations.AddIndex(
            model_name='teamoftheweekselection',
            index=models.Index(fields=['player', '-avg_rating'], name='league_team_player__3651b9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teamoftheweekselection',
            unique_together={('totw', 'player')},
        ),
    ]
