# Generated by Django 6.0.1 on 2026-01-31 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0007_season_clubs_alter_season_name_alter_season_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='knockoutmatch',
            name='away_placeholder',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='knockoutmatch',
            name='home_placeholder',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='knockoutmatch',
            name='away_club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knockout_away', to='league.club'),
        ),
        migrations.AlterField(
            model_name='knockoutmatch',
            name='home_club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knockout_home', to='league.club'),
        ),
    ]
