# Generated by Django 6.0.1 on 2026-02-25 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0008_teamoftheweek_teamoftheweekselection_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamoftheweek',
            options={'ordering': ['-season__year', 'week_type', 'totw_number']},
        ),
        migrations.RemoveIndex(
            model_name='teamoftheweek',
            name='league_team_season__c10fcc_idx',
        ),
        migrations.AlterUniqueTogether(
            name='teamoftheweek',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='teamoftheweek',
            name='end_gameweek',
            field=models.IntegerField(blank=True, help_text='Last gameweek included (e.g., 3 for weeks 1-3)', null=True),
        ),
        migrations.AddField(
            model_name='teamoftheweek',
            name='start_gameweek',
            field=models.IntegerField(blank=True, help_text='First gameweek included (e.g., 1 for weeks 1-3)', null=True),
        ),
        migrations.AddField(
            model_name='teamoftheweek',
            name='totw_number',
            field=models.IntegerField(default=1, help_text='TOTW number (1, 2, 3, etc.)'),
        ),
        migrations.AlterField(
            model_name='playermatchstats',
            name='minutes_played',
            field=models.IntegerField(default=90),
        ),
        migrations.AlterField(
            model_name='playermatchstats',
            name='rating',
            field=models.FloatField(default=6.0),
        ),
        migrations.AlterField(
            model_name='teamoftheweek',
            name='week_number',
            field=models.IntegerField(default=1, help_text='Legacy field - use totw_number instead'),
        ),
        migrations.AlterUniqueTogether(
            name='teamoftheweek',
            unique_together={('season', 'totw_number', 'week_type')},
        ),
        migrations.AddIndex(
            model_name='teamoftheweek',
            index=models.Index(fields=['season', 'week_type', 'totw_number'], name='league_team_season__3e6d22_idx'),
        ),
    ]
