# Generated by Django 6.0.1 on 2026-02-26 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0009_alter_teamoftheweek_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamoftheweekselection',
            name='skill_rating',
            field=models.FloatField(default=0, help_text='Skill rating during this period (80% rating + 20% contributions)'),
        ),
        migrations.AddIndex(
            model_name='teamoftheweekselection',
            index=models.Index(fields=['position', '-skill_rating'], name='league_team_positio_4ab22c_idx'),
        ),
    ]
