# Generated by Django 6.0.1 on 2026-07-28 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0010_teamoftheweekselection_skill_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftFranchise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_title', models.CharField(default='DRAFT LEAGUE 2.0', max_length=100)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('owner_name', models.CharField(max_length=120)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='league/pplLogos/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DraftFranchisePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squad_entries', to='league.draftfranchise')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_entries', to='league.player')),
            ],
            options={
                'ordering': ['-sold_price', 'player__gamertag'],
                'indexes': [models.Index(fields=['franchise', '-sold_price'], name='league_draf_franchi_b38c53_idx'), models.Index(fields=['player'], name='league_draf_player__aacdca_idx')],
                'unique_together': {('franchise', 'player')},
            },
        ),
    ]
